# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Build and Test

on:
  workflow_dispatch:
  push:
    branches: ["**"]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
#        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}
#        GH_CUSTOM_ANNOTATIONS_TOKEN: ${{ secrets.GH_CUSTOM_ANNOTATIONS_TOKEN }}
